# Generated by Django 4.2.20 on 2025-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Duminda Nadeeshan', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('delete', 'Deleted'), ('deactivate', 'Deactivated'), ('reactivate', 'Reactivated')], max_length=20),
        ),
    ]
