# Generated by Django 4.2.20 on 2025-05-01 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('health_issues', models.TextField(blank=True)),
                ('class_level', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('guardian', models.ForeignKey(blank=True, limit_choices_to={'role': 'guardian'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
