# Generated by Django 4.2.20 on 2025-06-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_class_level_alter_student_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='health_issues',
        ),
    ]
