# Generated by Django 4.2.20 on 2025-06-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_health_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(choices=[('Rev', 'Rev'), ('Mr', 'Mr')], default='Rev', max_length=10),
            preserve_default=False,
        ),
    ]
