# Generated by Django 4.2.20 on 2025-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(choices=[('Primary Section', 'Primary Section'), ('Oriental Section', 'Oriental Section'), ('Primary and Oriental Section', 'Primary and Oriental Section')], max_length=50),
        ),
    ]
