# Generated by Django 4.2.20 on 2025-07-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0008_student_gender'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefect_type', models.CharField(choices=[('Senior Head Prefect', 'Senior Head Prefect'), ('Senior Deputy Head Prefect', 'Senior Deputy Head Prefect'), ('Prefect (Oriental Section)', 'Prefect (Oriental Section)'), ('Student Services Coordinator', 'Student Services Coordinator'), ('Junior Head Prefect', 'Junior Head Prefect'), ('Junior Deputy Head Prefect', 'Junior Deputy Head Prefect'), ('Class Monitor', 'Class Monitor')], max_length=255)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('class_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_level', to='clases.class')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefect', to='students.student')),
            ],
        ),
    ]
