# Generated by Django 4.2.20 on 2025-07-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
        ('students', '0008_student_gender'),
        ('prefects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefect',
            name='class_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.class'),
        ),
        migrations.AlterField(
            model_name='prefect',
            name='prefect_type',
            field=models.CharField(choices=[('senior_head', 'Senior Head Prefect'), ('senior_deputy_head', 'Senior Deputy Head Prefect'), ('prefect_oriental', 'Prefect (Oriental Section)'), ('student_services_coordinator', 'Student Services Coordinator'), ('junior_head', 'Junior Head Prefect'), ('junior_deputy_head', 'Junior Deputy Head Prefect'), ('class_monitor', 'Class Monitor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prefect',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
