# Generated by Django 4.2.20 on 2025-07-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_gender'),
        ('prefects', '0002_alter_prefect_class_level_alter_prefect_prefect_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefect',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
