# Generated by Django 4.2.20 on 2025-07-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_gender'),
        ('clases', '0001_initial'),
        ('prefects', '0004_alter_prefect_class_level_alter_prefect_prefect_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefect',
            name='year',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prefect',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_level', to='clases.class'),
        ),
        migrations.AlterField(
            model_name='prefect',
            name='prefect_type',
            field=models.CharField(choices=[('Senior Head Prefect', 'Senior Head Prefect'), ('Senior Deputy Head Prefect', 'Senior Deputy Head Prefect'), ('Prefect (Oriental Section)', 'Prefect (Oriental Section)'), ('Student Services Coordinator', 'Student Services Coordinator'), ('Junior Head Prefect', 'Junior Head Prefect'), ('Junior Deputy Head Prefect', 'Junior Deputy Head Prefect'), ('Prefect (Primary Section)', 'Prefect (Primary Section)'), ('Class Monitor', 'Class Monitor')], max_length=255),
        ),
        migrations.AlterField(
            model_name='prefect',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefect', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='prefect',
            unique_together={('student', 'year')},
        ),
    ]
