# Generated by Django 4.2.20 on 2025-07-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefects', '0005_prefect_year_alter_prefect_class_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefect',
            name='year',
            field=models.CharField(),
        ),
    ]
