# Generated by Django 4.2.20 on 2025-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefects', '0006_alter_prefect_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefect',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
