# Generated by Django 4.2.20 on 2025-06-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_gender'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examattendee',
            unique_together={('student', 'exam')},
        ),
    ]
