# Generated by Django 4.2.20 on 2025-07-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examattendee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='academic_year',
            field=models.PositiveIntegerField(),
        ),
    ]
