# Generated by Django 4.2.20 on 2025-06-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('teachers', '0002_alter_teacher_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.section'),
        ),
    ]
