# Generated by Django 4.2.20 on 2025-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('Rev', 'Rev'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10),
        ),
    ]
