# Generated by Django 4.2.20 on 2025-07-08 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheritem',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
