# Generated by Django 4.2.20 on 2025-07-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0008_student_gender'),
        ('teachers', '0004_alter_teacher_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=7)),
                ('document_type', models.CharField(choices=[('NIC', 'NIC'), ('Passport', 'Passport'), ('Birth Certificate', 'Birth Certificate'), ('Samanera Certificate', 'Samanera Certificate'), ('Upasampada Certificate', 'Upasampada Certificate'), ('School Leaving Certificate', 'School Leaving Certificate'), ('Competition Certificate', 'Competition Certificate')], max_length=50)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
