# Generated by Django 4.2.20 on 2025-06-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveallocation',
            name='year',
            field=models.CharField(default=2025, max_length=4),
            preserve_default=False,
        ),
    ]
