# Generated by Django 4.2.20 on 2025-06-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_title'),
        ('leaves', '0002_leaveallocation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveallocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
