# Generated by Django 4.2.20 on 2025-06-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_title'),
        ('leaves', '0003_alter_leaveallocation_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveallocation',
            unique_together={('teacher', 'year')},
        ),
    ]
