# Generated by Django 4.2.20 on 2025-07-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leaveallocation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveallocation',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
