# Generated by Django 4.2.20 on 2025-06-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_profile_photo'),
        ('teachers', '0003_alter_teacher_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=7)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('eye_glasses', models.BooleanField(default=False)),
                ('physical_challenge', models.BooleanField(default=False)),
                ('major_diseases', models.BooleanField(default=False)),
                ('regular_checkup_required', models.BooleanField(default=False)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
