# Generated by Django 4.2.20 on 2025-07-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='bmi',
            field=models.FloatField(default=0.7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='status',
            field=models.CharField(default='Healthy'),
            preserve_default=False,
        ),
    ]
